apiVersion: apps/v1
kind: Deployment
metadata:
  name: vitrine
  namespace: vitrine
  labels:
    app: vitrine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vitrine
  template:
    metadata:
      labels:
        app: vitrine
    spec:
      containers:
        - name: nginx
          image: nginx:1.30-alpina
          ports:
            - containerPort: 80
